### ISSUE TITLE
Descending ordering is not handled

### ISSUE THREAD

**Issue by SafaAlfulaij** [matthiask/django-tree-queries#15] opened 2021-05-12 13:16 UTC
Example:
```python
class Model(TreeNode):
    class Meta:
        ordering = ("-created_at",)
```

generates an SQL containing (sqlite):
```sql
 
     WITH RECURSIVE __tree(tree_depth, tree_path, tree_ordering, tree_pk) AS 
 (
         SELECT
             0 tree_depth,
             printf("\x1f%%s\x1f", id) tree_path,
             printf("\x1f%%020s\x1f", -created_at) tree_ordering, # maybe invalid SQL
             T."id" tree_pk
         FROM my_model_table T
         WHERE T."parent_id" IS NULL
 
         UNION ALL
 
         SELECT
             __tree.tree_depth + 1,
             __tree.tree_path || printf("%%s\x1f", T.id),
             __tree.tree_ordering || printf("%%020s\x1f", T.-created_at), # invalid SQL
             T."id"
         FROM my_model_table T
         JOIN __tree ON T."parent_id" = __tree.tree_pk
     )
```

**Comment by matthiask** [comment] 2021-05-12 13:21
Yes, that's true. This came up once already here https://github.com/matthiask/django-tree-queries/issues/6 but no solution exists (yet) for this.

**Comment by matthiask** [comment] 2022-06-11 07:54
Duplicate of #6

**Closed by matthiask** 2022-06-11 07:54 UTC
Labels: enhancement
